sonar.projectKey=IY-481
sonar.host.url=http://localhost:9000
sonar.token=YOUR_TOKEN

sonar.sources=.
sonar.inclusions=apps/api/plane/app/views/search/base.py,\
apps/api/plane/app/views/issue/base.py,\
apps/api/plane/bgtasks/issue_activities_task.py