sonar-scanner \
  -Dsonar.projectKey=IY-481 \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.token=sqp_bbcc99ee1db327b5bcf7dae640923cbf9828d548 \
  -Dsonar.sources=apps/api/plane/app/views/search,apps/api/plane/app/views/issue,apps/api/plane/bgtasks \
  -Dsonar.inclusions=apps/api/plane/app/views/search/base.py,apps/api/plane/app/views/issue/base.py,apps/api/plane/bgtasks/issue_activities_task.py